name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Updated to the latest version
        with:
          node-version: '16' # You can also set this to '20' to be future-proof

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test
